### ISSUE TITLE
black settings not in pyproject.toml

### ISSUE THREAD

**Issue by skewty** [ijl/orjson#30]
If you are using **black** perhaps you should include the settings you use in `pyproject.toml` so other contributors also have them and they get applied automatically.

Something like:

```toml
[tool.black]
line-length = 120
target-version = ['py36', 'py37']
skip-string-normalization = "true"
```
