### ISSUE TITLE
Python 3.13 with no gil - SystemError: init function of orjson returned uninitialized object

### ISSUE THREAD

**Issue by prabhu** [ijl/orjson#520]
I am getting this error, while testing my project with python 3.13 with free-threading. Used the below code snippet to setup this in GitHub actions.

```
- name: Set up Python
       uses: deadsnakes/action@v3.2.0
       with:
         python-version: '3.13'
         nogil: true
```

Example failure:
https://github.com/AppThreat/vulnerability-db/actions/runs/11240903455/job/31251265074#step:9:152
